name: Build release zip

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin # Remove or modify this step as needed
      run: |
        echo Building...
    
    - name: Zip artifact for deployment
      run: zip release.zip ./* -r
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: bridge-game
        path: release.zip
