name: Build release zip

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin
      run: |
        echo Building...
          
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "{VersionCounter}"
        replace: ${{ github.run_number }}
        regex: false
          
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: bridge-game
        path: 
          ./**
          !./.git/**
          !./.github/**
